# Generated by Django 3.1.7 on 2021-03-02 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('NB', 'Non-binary person'), ('NN', 'Not selected')], default='NN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='name',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z ]+', 'Invalid name')]),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='phone',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator('\\+\\d{12}', 'Invalid phone')]),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='position',
            field=models.CharField(choices=[('MA', 'MR'), ('DE', 'DV')], default='MA', max_length=2, null=True),
        ),
    ]
