# Generated by Django 3.1.7 on 2021-03-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210323_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='projecttaskcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
