# Generated by Django 3.1.7 on 2021-03-02 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advice', '0002_advicecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advicecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
